In [1]:
from untangling.utils.interface_rws_BRIO import Interface, ABB_WHITE
import numpy as np
from yumiplanning.yumi_kinematics import YuMiKinematics as YK

SPEED = (0.4, 6 * np.pi)
iface = Interface(
    ABB_WHITE.as_frames(YK.l_tcp_frame, YK.l_tip_frame),
    ABB_WHITE.as_frames(YK.r_tcp_frame, YK.r_tip_frame),
    speed=SPEED,
)

/home/mallika/anaconda3/envs/lipnew/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
r_pos = iface.y.right.get_pose()
print(r_pos)

Tra: [ 0.39513227 -0.45487944  0.19852412]
 Rot: [[ 0.96437471 -0.26356552 -0.02268543]
 [-0.26442585 -0.95788879 -0.11192871]
 [ 0.00777043  0.11393983 -0.99345726]]
 Qtn: [ 0.05707158  0.98940901 -0.13341079 -0.00376866]
 from r_tcp to base_link


In [3]:
l_pos = iface.y.left.get_pose()
print(l_pos)

Tra: [0.4029946  0.46106334 0.24193466]
 Rot: [[ 0.97672978  0.21376282  0.01744685]
 [ 0.21100633 -0.97232284  0.1003226 ]
 [ 0.03840921 -0.09430667 -0.99480198]]
 Qtn: [-0.04900244  0.99295702  0.1069455   0.01406306]
 from l_tcp to base_link


In [4]:
from decluttering.deprecated.push_through_backup2 import get_poi_and_vec_for_push, perform_push_through, perform_pindown, perform_pick_away, perform_point_grasp, drop_in_bin
from decluttering.deprecated.demopipeline import DemoPipeline

# def initialize_pipeline(logLevel):
#     pipeline = DemoPipeline(viz=False, loglevel=logLevel, initialize_iface=True)
#     pipeline.iface.open_grippers()
#     pipeline.iface.sync()
#     pipeline.iface.home()
#     pipeline.iface.sync()
#     return pipeline

# pipeline = initialize_pipeline('DEBUG')

iface.open_grippers()
iface.sync()

iface.arms_clear_home()
iface.sync()
# drop_in_bin(pipeline)

Info:    RRTConnect: Starting planning with 1 states already in datastructure
Info:    RRTConnect: Created 4 states (2 start + 2 goal)
Info:    Solution found in 0.002206 seconds
Info:    SimpleSetup: Path simplification took 0.007443 seconds and changed from 3 to 2 states
Solution cost 7.48663e-06
move joints
